### ISSUE TITLE
identifier containing /

### ISSUE THREAD

**Issue by atomotic** [lmika/oaipmh#1]
is common for dspace repositories to publish oai identifiers containing a slash char:
eg. **oai:padis.uniroma1.it:10805/526**

this breaks the harvest, the destination file name needs to be sanitized 

   ➜  oaipmh -p="didl" 'http://padis.uniroma1.it/oai/request' harvest -s hdl_10805_329
    panic: open 20150213T133934/01/oai:padis.uniroma1.it:10805/526.xml: no such file or directory

**Comment by lmika-bom** [comment]
Have managed to recreate the issue locally.  This has been fixed by escaping the identifiers using a similar process to [RFC 3986](http://www.ietf.org/rfc/rfc3986.txt):
- All apha-numeric characters pass through unescaped.
- The characters `-`, `_`, `:` and `.` pass through unescaped.
- Anything else is escaped as hex strings and prefixed with `%` in a similar way for URLs.

These file-names should be unescapable using a function like the `QueryUnescape()` function provided by Go in `net/url`.

Merged into master and pushed to origin.
